name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: stack-spot/stk-cli-action@v1.1
        with:
          client_id: ${{ secrets.STK_CLIENT_ID }}
          client_key: ${{ secrets.STK_CLIENT_KEY }}
          realm: ${{ secrets.STK_REALM }}
      - name: Exec StackSpot AI
        id: stack_spot_exec
        run: |
          stk ai
          como obter a resposta de um select mysql via terminal via python sendo que o client mysql não é finalizado? 
