name: AI Code Reviewer


on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: "Get diff of the pull request"
        id: get_diff
        shell: bash
        env:
          PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
        run: |-
          git fetch origin "${{ env.PULL_REQUEST_HEAD_REF }}:${{ env.PULL_REQUEST_HEAD_REF }}"
          git checkout "${{ env.PULL_REQUEST_HEAD_REF }}"
          git diff "origin/${{ env.PULL_REQUEST_HEAD_REF }}" > "diff.txt"
          # shellcheck disable=SC2086
          echo "diff=$(cat "diff.txt")" >> $GITHUB_ENV

      - uses: stack-spot/stk-cli-action@v1.1
        with:
          client_id: ${{ secrets.STK_CLIENT_ID }}
          client_key: ${{ secrets.STK_CLIENT_KEY }}
          realm: ${{ secrets.STK_REALM }}
          github_repository: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_pull_request_number: 2
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
          pull_request_diff: |-
            ${{ steps.get_diff.outputs.pull_request_diff }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests pip install pexpect pip install keyboard pip install click pip install click loguru

      - name: Execute Python Script
        id: python_exec
        env:
          client_id: ${{ secrets.STK_CLIENT_ID }}
          client_key: ${{ secrets.STK_CLIENT_KEY }}
          realm: ${{ secrets.STK_REALM }}
          github_repository: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_pull_request_number: 2
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
          pull_request_diff: |-
            ${{ steps.get_diff.outputs.pull_request_diff }}
        run: |-
          python application.py
