name: AI Code Reviewer

on: [push]
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Teste run
        run: echo 'Hello World'
          