name: AI Code Reviewer


on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "LICENSE"
    
jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: "Get diff of the pull request"
        id: get_diff
        shell: bash
        env:
          PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
          DEFAULT_BRANCH: "${{ github.event.repository.default_branch }}"
        run: |-
          # Fetch the default branch
          git fetch origin "${{ env.DEFAULT_BRANCH }}"
          # Exclude png files from diff
          git diff "origin/${{ env.DEFAULT_BRANCH }}" ":(exclude)*.png" > "diff.txt"
          # Put multi-line string into an environment variable
          # shellcheck disable=SC2086
          {
            echo "pull_request_diff<<EOF";
            cat "diff.txt";
            echo 'EOF';
          } >> $GITHUB_OUTPUT

      - uses: stack-spot/stk-cli-action@v1.1
        with:
          client_id: ${{ secrets.STK_CLIENT_ID }}
          client_key: ${{ secrets.STK_CLIENT_KEY }}
          realm: ${{ secrets.STK_REALM }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: test sh install
        run:
           sudo apt-get install -y expect
      
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests pip install pexpect pip install keyboard pip install click pip install click loguru

      - name: Execute Python Script
        id: python_exec
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
          PULL_REQUEST_DIFF: ${{ steps.get_diff.outputs.pull_request_diff }}
        run: |-
          python application.py